### ISSUE TITLE
用户权限怎么设置？

### ISSUE THREAD

**Issue by AiMing317** [watchdog-framework/watchdog-framework#4]
想问下我使用admin用户登录时，所有权限军没有。权限设置时数据库字段定义还是哪里？密码加密时什么方式？

**Comment by Licoy** [comment]
请检查一下配置，确认Redis正常可用，另外密码相关请参考https://github.com/watchdog-framework/watchdog-framework/blob/master/src/main/java/cn/licoy/wdog/core/config/shiro/CredentialsMatcher.java
